// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using CoreFoundation;
using Foundation;
using UIKit;

namespace Xamarin_Sample_App
{
	public partial class CartTableViewCell : UITableViewCell
	{
		public CartTableViewCell (IntPtr handle) : base (handle)
		{
		}

        public void UpdateRowsAsync(List<Product> products, NSIndexPath indexPath)
        {
            productName.Text = products[indexPath.Row].name;
            var totalPrice = Int16.Parse(products[indexPath.Row].price)*products[indexPath.Row].qty;
            productPrice.Text = "$ " + totalPrice.ToString();

            stepper.Tag = indexPath.Row;
            stepper.Value = (Double)products[indexPath.Row].qty;
            quantityLabel.Text = products[indexPath.Row].qty.ToString();
            string imageURL = products[indexPath.Row].image;
            SetImage(imageURL);
        }

        private void SetImage(string url)
        {
            productImage.Image = null;
            var service = new Services();
            service.DownloadImage(url, completionBlock: (data) =>
            {
                productImage.Image = UIImage.LoadFromData(data);
            });
        }
    }
}
