// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Xamarin_Sample_App
{
	public partial class SampleUIViewController : UIViewController
	{
		public SampleUIViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        partial void SliderAction(NSObject sender)
        {
            sliderLabel.Text = slider.Value.ToString();
        }

        partial void colorWellAction(NSObject sender)
        {
            View.BackgroundColor = colorWell.SelectedColor;
        }
    }
}
