// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;
using CoreFoundation;

namespace Xamarin_Sample_App.Home
{
	public partial class CategoryCollectionViewCell : UICollectionViewCell
	{
		public CategoryCollectionViewCell(IntPtr handle) : base (handle)
		{
		}

		public void UpdateRows(List<CategoryModel> category, NSIndexPath indexPath)
		{
			itemLabel.Text = category[indexPath.Row].categoryLabel;
			string imageURL = category[indexPath.Row].categoryImage;
			SetImage(imageURL);	
		}

		private void SetImage(string url)
		{
            collectionImageView.Image = null;
            var service = new Services();
            service.DownloadImage(url,completionBlock : (data) =>
            {
                collectionImageView.Image = UIImage.LoadFromData(data);
            });
        }
	}
}