// This file has been autogenerated from a class added in the UI designer.

using System;
using Xamarin_Sample_App.Home;
using Foundation;
using UIKit;
using KountDataCollector;
using System.Collections.Generic;

namespace Xamarin_Sample_App
{
	public partial class LoginViewController : KountAnalyticsViewController
	{
        List<User> users = new List<User>();

        public LoginViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitializeKountSDK();
            GetUserData();
            NavigationItem.SetHidesBackButton(true, animated: true);
            DismissKeyboard();
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            passwordField.Text = "";
        }

        partial void signUpButton(NSObject sender)
        {
            NavigateToSignUp();
        }

        partial void loginButton(NSObject sender)
        {
            bool valid = IsValid();

            if (valid)
            {
                KountAnalyticsViewController.SharedInstance.StoreLogInEvents(true);
                NavigateToHome();
            }
            else
            {
                KountAnalyticsViewController.SharedInstance.StoreLogInEvents(false);
                ShowAlert();
            }
        }

        
        private void GetUserData()
        {
            var service = new UserService();
            users = service.getData();
        }

        private void NavigateToSignUp()
        {   
            var signUpViewController = Storyboard.InstantiateViewController("SignUpViewController") as SignUpViewController;
            this.NavigationController.PushViewController(signUpViewController, true);
        }

        private void NavigateToHome()
        {
            var tabBarController = Storyboard.InstantiateViewController("TabViewController") as TabViewController;
            this.NavigationController.PushViewController(tabBarController, true);
        }

        private bool IsValid()
        {
            bool check = false;

            if (usernameField.Text == users[0].username && passwordField.Text == users[0].password)
            {
                check = true;
            }
            return check;
        }

        private void ShowAlert()
        {
            var alert = UIAlertController.Create("Incorrect", "Username or Password is incorrect", UIAlertControllerStyle.Alert);
            alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));
            PresentViewController(alert, true, null);
        }

        private void DismissKeyboard()
        {
            // Dismiss the keyboard if taps anywhere in the view.
            var gesture = new UITapGestureRecognizer(() =>
              View.EndEditing(true));
            View.AddGestureRecognizer(gesture);
        }

        private void InitializeKountSDK()
        {
            // Method to call Kount Data collector and it's configurations.
            KountDataCollector.KDataCollector.SharedCollector.MerchantID = 900900;
            KountDataCollector.KDataCollector.SharedCollector.Environment = KountDataCollector.KEnvironment.Test;
            KountDataCollector.KDataCollector.SharedCollector.Debug = true;
            KountDataCollector.KDataCollector.SharedCollector.LocationCollectorConfig = KountDataCollector.KLocationCollectorConfig.RequestPermission;
            KountDataCollector.KountAnalyticsViewController.SharedInstance.SetEnvironmentForAnalytics(KountDataCollector.KDataCollector.SharedCollector.Environment);

            KountDataCollector.KountAnalyticsViewController.SharedInstance.Collect(SessionID, true,
                completionBlock: (sessionID, success, error) =>
                {
                    if (success)
                    {
                        Console.WriteLine("Collection Successful");
                    }
                    else
                    {
                        if (error != null)
                        {
                            Console.WriteLine("Collection Failed with error ", error);
                        }
                        else
                        {
                            Console.WriteLine("Collection failed without error");
                        }
                    }
                }
                );

            
        }
    }
}
