// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;

namespace Xamarin_Sample_App
{
	public partial class ProfileViewController : UIViewController
	{
		public ProfileViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        partial void LogoutTap(NSObject sender)
        {
            NavigateToLogin();
        }

        private void NavigateToLogin()
        {
            var loginViewController = Storyboard.InstantiateViewController("LoginViewController") as LoginViewController;
            this.NavigationController.PopToRootViewController(true);
        }
    }
}
