// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;

namespace Xamarin_Sample_App
{
	public partial class AddressViewController : UIViewController
	{
		public AddressViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            DismissKeyboard();
        }

        partial void ContinueTap(NSObject sender)
        {
            NavigateToPayment();
        }

        private void NavigateToPayment()
        {
            var paymentViewController = Storyboard.InstantiateViewController("PaymentViewController") as PaymentViewController;
            this.NavigationController.PushViewController(paymentViewController, true);
        }

        private void DismissKeyboard()
        {
            // Dismiss the keyboard if taps anywhere in the view.
            var gesture = new UITapGestureRecognizer(() =>
              View.EndEditing(true));
            View.AddGestureRecognizer(gesture);
        }
    }
}
